"""empty message

Revision ID: 97e729bf0db9
Revises: 14226de2bca6
Create Date: 2024-08-03 09:27:34.867720

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97e729bf0db9"
down_revision = "14226de2bca6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("password_hash", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
