"""empty message

Revision ID: ace51bcfab0b
Revises: 
Create Date: 2024-08-09 09:48:30.723028

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ace51bcfab0b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Symbol", sa.String(length=8), nullable=False),
        sa.Column("AssetType", sa.String(length=50), nullable=False),
        sa.Column("Name", sa.String(length=255), nullable=False),
        sa.Column("Description", sa.Text(), nullable=True),
        sa.Column("CIK", sa.String(length=20), nullable=True),
        sa.Column("Exchange", sa.String(length=10), nullable=True),
        sa.Column("Currency", sa.String(length=10), nullable=True),
        sa.Column("Country", sa.String(length=50), nullable=True),
        sa.Column("Sector", sa.String(length=50), nullable=True),
        sa.Column("Industry", sa.String(length=50), nullable=True),
        sa.Column("Address", sa.String(length=255), nullable=True),
        sa.Column("OfficialSite", sa.String(length=255), nullable=True),
        sa.Column("FiscalYearEnd", sa.String(length=20), nullable=True),
        sa.Column("LatestQuarter", sa.String(length=20), nullable=True),
        sa.Column("MarketCapitalization", sa.Integer(), nullable=True),
        sa.Column("EBITDA", sa.Integer(), nullable=True),
        sa.Column("PERatio", sa.Float(), nullable=True),
        sa.Column("PEGRatio", sa.Float(), nullable=True),
        sa.Column("BookValue", sa.Float(), nullable=True),
        sa.Column("DividendPerShare", sa.Float(), nullable=True),
        sa.Column("DividendYield", sa.Float(), nullable=True),
        sa.Column("EPS", sa.Float(), nullable=True),
        sa.Column("RevenuePerShareTTM", sa.Float(), nullable=True),
        sa.Column("ProfitMargin", sa.Float(), nullable=True),
        sa.Column("OperatingMarginTTM", sa.Float(), nullable=True),
        sa.Column("ReturnOnAssetsTTM", sa.Float(), nullable=True),
        sa.Column("ReturnOnEquityTTM", sa.Float(), nullable=True),
        sa.Column("RevenueTTM", sa.Integer(), nullable=True),
        sa.Column("GrossProfitTTM", sa.Integer(), nullable=True),
        sa.Column("DilutedEPSTTM", sa.Float(), nullable=True),
        sa.Column("QuarterlyEarningsGrowthYOY", sa.Float(), nullable=True),
        sa.Column("QuarterlyRevenueGrowthYOY", sa.Float(), nullable=True),
        sa.Column("AnalystTargetPrice", sa.Float(), nullable=True),
        sa.Column("AnalystRatingStrongBuy", sa.Integer(), nullable=True),
        sa.Column("AnalystRatingBuy", sa.Integer(), nullable=True),
        sa.Column("AnalystRatingHold", sa.Integer(), nullable=True),
        sa.Column("AnalystRatingSell", sa.Integer(), nullable=True),
        sa.Column("AnalystRatingStrongSell", sa.Integer(), nullable=True),
        sa.Column("TrailingPE", sa.Float(), nullable=True),
        sa.Column("ForwardPE", sa.Float(), nullable=True),
        sa.Column("PriceToSalesRatioTTM", sa.Float(), nullable=True),
        sa.Column("PriceToBookRatio", sa.Float(), nullable=True),
        sa.Column("EVToRevenue", sa.Float(), nullable=True),
        sa.Column("EVToEBITDA", sa.Float(), nullable=True),
        sa.Column("Beta", sa.Float(), nullable=True),
        sa.Column("_52WeekHigh", sa.Float(), nullable=True),
        sa.Column("_52WeekLow", sa.Float(), nullable=True),
        sa.Column("_50DayMovingAverage", sa.Float(), nullable=True),
        sa.Column("_200DayMovingAverage", sa.Float(), nullable=True),
        sa.Column("SharesOutstanding", sa.Integer(), nullable=True),
        sa.Column("DividendDate", sa.String(length=20), nullable=True),
        sa.Column("ExDividendDate", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("Symbol"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("password_hash", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("companies")
    # ### end Alembic commands ###
