"""empty message

Revision ID: e3896ec2c9a0
Revises: ace51bcfab0b
Create Date: 2024-08-09 10:00:58.450775

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e3896ec2c9a0"
down_revision = "ace51bcfab0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.alter_column(
            "MarketCapitalization",
            existing_type=mysql.INTEGER(display_width=11),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "EBITDA",
            existing_type=mysql.INTEGER(display_width=11),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "RevenueTTM",
            existing_type=mysql.INTEGER(display_width=11),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "GrossProfitTTM",
            existing_type=mysql.INTEGER(display_width=11),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "SharesOutstanding",
            existing_type=mysql.INTEGER(display_width=11),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.alter_column(
            "SharesOutstanding",
            existing_type=sa.BigInteger(),
            type_=mysql.INTEGER(display_width=11),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "GrossProfitTTM",
            existing_type=sa.BigInteger(),
            type_=mysql.INTEGER(display_width=11),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "RevenueTTM",
            existing_type=sa.BigInteger(),
            type_=mysql.INTEGER(display_width=11),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "EBITDA",
            existing_type=sa.BigInteger(),
            type_=mysql.INTEGER(display_width=11),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "MarketCapitalization",
            existing_type=sa.BigInteger(),
            type_=mysql.INTEGER(display_width=11),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
