"""empty message

Revision ID: e76034bfc3ee
Revises: 14226de2bca6
Create Date: 2024-07-25 15:46:50.732146

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e76034bfc3ee"
down_revision = "14226de2bca6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("register_date", sa.DateTime(), nullable=True),
        sa.Column("open_price", sa.Float(), nullable=True),
        sa.Column("close_price", sa.Float(), nullable=True),
        sa.Column("highest_price", sa.Float(), nullable=True),
        sa.Column("lowest_price", sa.Float(), nullable=True),
        sa.Column("transaction_volume", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("register_date"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_prices")
    # ### end Alembic commands ###
