services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme  # Set the root password
      MYSQL_DATABASE: profitprophet  # Create a database on startup
      MYSQL_USER: profitprophet  # Create a user
      MYSQL_PASSWORD: changeme  # Set the user's password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  flask-api:
    build:
      context: .
      dockerfile: docker/python-api/Dockerfile
    container_name: api
    ports:
      - "5000:5000"
      - "5678:5678"
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: profitprophet
    volumes:
      - ./app:/app

volumes:
  mariadb_data:

networks:
  my_network:
    driver: bridge